version: "3.9"

services:
  database:
    container_name: quiz-devpro_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - .env:/.env
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=quizdevpro
      - POSTGRES_USER=quizdevpro
    ports:
      - 5434:5432